export const countries = [
   { slug: 'indonesia', name: 'Indonesia' },
   { slug: 'malaysia', name: 'Malaysia' },
   { slug: 'singapore', name: 'Singapore' },
   { slug: 'thailand', name: 'Thailand' },
   { slug: 'philippines', name: 'Philippines' },
   { slug: 'vietnam', name: 'Vietnam' },
   { slug: 'laos', name: 'Laos' },
   { slug: 'cambodia', name: 'Cambodia' },
   { slug: 'myanmar', name: 'Myanmar' },
   { slug: 'brunei', name: 'Brunei' },
   { slug: 'timor-leste', name: 'Timor-Leste' },

   { slug: 'china', name: 'China' },
   { slug: 'japan', name: 'Japan' },
   { slug: 'south-korea', name: 'South Korea' },
   { slug: 'north-korea', name: 'North Korea' },
   { slug: 'mongolia', name: 'Mongolia' },
   { slug: 'taiwan', name: 'Taiwan' },

   { slug: 'india', name: 'India' },
   { slug: 'pakistan', name: 'Pakistan' },
   { slug: 'bangladesh', name: 'Bangladesh' },
   { slug: 'sri-lanka', name: 'Sri Lanka' },
   { slug: 'nepal', name: 'Nepal' },
   { slug: 'bhutan', name: 'Bhutan' },
   { slug: 'maldives', name: 'Maldives' },

   { slug: 'saudi-arabia', name: 'Saudi Arabia' },
   { slug: 'uae', name: 'United Arab Emirates' },
   { slug: 'qatar', name: 'Qatar' },
   { slug: 'kuwait', name: 'Kuwait' },
   { slug: 'bahrain', name: 'Bahrain' },
   { slug: 'oman', name: 'Oman' },
   { slug: 'yemen', name: 'Yemen' },
   { slug: 'iran', name: 'Iran' },
   { slug: 'iraq', name: 'Iraq' },
   { slug: 'turkey', name: 'Turkey' },
   { slug: 'jordan', name: 'Jordan' },
   { slug: 'lebanon', name: 'Lebanon' },
   { slug: 'syria', name: 'Syria' },
   { slug: 'israel', name: 'Israel' },
   { slug: 'palestine', name: 'Palestine' },

   { slug: 'united-kingdom', name: 'United Kingdom' },
   { slug: 'ireland', name: 'Ireland' },
   { slug: 'france', name: 'France' },
   { slug: 'germany', name: 'Germany' },
   { slug: 'netherlands', name: 'Netherlands' },
   { slug: 'belgium', name: 'Belgium' },
   { slug: 'luxembourg', name: 'Luxembourg' },
   { slug: 'switzerland', name: 'Switzerland' },
   { slug: 'austria', name: 'Austria' },
   { slug: 'italy', name: 'Italy' },
   { slug: 'spain', name: 'Spain' },
   { slug: 'portugal', name: 'Portugal' },
   { slug: 'andorra', name: 'Andorra' },
   { slug: 'monaco', name: 'Monaco' },
   { slug: 'liechtenstein', name: 'Liechtenstein' },

   { slug: 'sweden', name: 'Sweden' },
   { slug: 'norway', name: 'Norway' },
   { slug: 'finland', name: 'Finland' },
   { slug: 'denmark', name: 'Denmark' },
   { slug: 'iceland', name: 'Iceland' },

   { slug: 'poland', name: 'Poland' },
   { slug: 'czechia', name: 'Czechia' },
   { slug: 'slovakia', name: 'Slovakia' },
   { slug: 'hungary', name: 'Hungary' },
   { slug: 'romania', name: 'Romania' },
   { slug: 'bulgaria', name: 'Bulgaria' },
   { slug: 'croatia', name: 'Croatia' },
   { slug: 'serbia', name: 'Serbia' },
   { slug: 'bosnia-and-herzegovina', name: 'Bosnia and Herzegovina' },
   { slug: 'slovenia', name: 'Slovenia' },
   { slug: 'montenegro', name: 'Montenegro' },
   { slug: 'north-macedonia', name: 'North Macedonia' },
   { slug: 'albania', name: 'Albania' },
   { slug: 'greece', name: 'Greece' },

   { slug: 'russia', name: 'Russia' },
   { slug: 'ukraine', name: 'Ukraine' },
   { slug: 'belarus', name: 'Belarus' },
   { slug: 'moldova', name: 'Moldova' },
   { slug: 'georgia', name: 'Georgia' },
   { slug: 'armenia', name: 'Armenia' },
   { slug: 'azerbaijan', name: 'Azerbaijan' },

   { slug: 'australia', name: 'Australia' },
   { slug: 'new-zealand', name: 'New Zealand' },
   { slug: 'fiji', name: 'Fiji' },
   { slug: 'papua-new-guinea', name: 'Papua New Guinea' },
   { slug: 'samoa', name: 'Samoa' },
   { slug: 'tonga', name: 'Tonga' },
   { slug: 'vanuatu', name: 'Vanuatu' },
   { slug: 'solomon-islands', name: 'Solomon Islands' },
   { slug: 'micronesia', name: 'Micronesia' },
   { slug: 'kiribati', name: 'Kiribati' },
   { slug: 'marshall-islands', name: 'Marshall Islands' },
   { slug: 'palau', name: 'Palau' },
   { slug: 'tuvalu', name: 'Tuvalu' },
   { slug: 'nauru', name: 'Nauru' },

   { slug: 'united-states', name: 'United States' },
   { slug: 'canada', name: 'Canada' },
   { slug: 'mexico', name: 'Mexico' },

   { slug: 'guatemala', name: 'Guatemala' },
   { slug: 'honduras', name: 'Honduras' },
   { slug: 'el-salvador', name: 'El Salvador' },
   { slug: 'nicaragua', name: 'Nicaragua' },
   { slug: 'costa-rica', name: 'Costa Rica' },
   { slug: 'panama', name: 'Panama' },

   { slug: 'cuba', name: 'Cuba' },
   { slug: 'dominican-republic', name: 'Dominican Republic' },
   { slug: 'haiti', name: 'Haiti' },
   { slug: 'jamaica', name: 'Jamaica' },
   { slug: 'bahamas', name: 'Bahamas' },
   { slug: 'trinidad-and-tobago', name: 'Trinidad and Tobago' },

   { slug: 'brazil', name: 'Brazil' },
   { slug: 'argentina', name: 'Argentina' },
   { slug: 'chile', name: 'Chile' },
   { slug: 'uruguay', name: 'Uruguay' },
   { slug: 'paraguay', name: 'Paraguay' },
   { slug: 'bolivia', name: 'Bolivia' },
   { slug: 'peru', name: 'Peru' },
   { slug: 'ecuador', name: 'Ecuador' },
   { slug: 'colombia', name: 'Colombia' },
   { slug: 'venezuela', name: 'Venezuela' },
   { slug: 'guyana', name: 'Guyana' },
   { slug: 'suriname', name: 'Suriname' },
];
